name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd noethysweb/noethysweb && cp settings_production_modele.py settings_production.py
        cd .. && python manage.py makemigrations
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic
        python manage.py createsuperuser
        python manage.py update_permissions
        python manage.py test
